### PR TITLE
Architecture discussion

### PR DESCRIPTION
**Pull request by mcataford**
Let's figure this out. :brain:

### CODE REVIEW

**Comment by noahnu** [comment]
For the frontend I'm thinking we enforce a modular pattern via yarn workspaces. So in the frontend directory we can have workspaces for:
- ui: UI Components, purely presentational
- utils: Things like date formatters, functional utils (e.g. memoization), etc..
- app (or core): main entry, essentially the containers
- storage: cache, persistance storage client
- ...

There's a question of where does the state/store live? App?

If the state is completely separate from the rest of the app, we could ship it in a service worker which would be interesting. Could setup some sort of proxy for a custom redux Provider implementation

**Comment by mcataford** [comment]
I haven't worked a whole lot with service workers, how would that work? State lives in SW and we mess with Redux so that actions and selectors reach out to the SW, and on state updates it would post some messages back?

re:workspaces, agreed, maximum containment / modularization that way. re:storage, we can do something fancy with localStorage / indexedDB depending what kind of data we want to store.

**Comment by mcataford** [comment]
@noahnu Do you still have interest in this? I certainly do and would love to get back in the soup. ⌨️

**Comment by noahnu** [comment]
Not sure how much time I'd be able to put into this, but happy to start it out and see where it takes us. I'd revise some initial points though, notably: drop redux

**Pull request closed without merging**
